import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useRouter } from 'next/router'
import { useEffect } from 'react'
import { CircularProgress } from '@mui/material'
import {SESSION} from './constants/Constants';

export default function Home() {

  const router = useRouter();

  useEffect(() =>{
    const userObject = JSON.parse(localStorage.getItem(SESSION));
    if(userObject){
      router.push("/app/home")
    } else{
      router.push("/login");
    }
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Plants Watering App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <CircularProgress/>
      </div>
    </div>
  )
}
